package viikko6;
// ENTITY CLASS, KOHDELUOKKA
public class Tili {
	// TÄLLE LUOKALLE ESITELLÄÄN OMINAISUUS
	// ELI ATTRIBUUTTI, NÄIHIN "TALLENNETAAN" OLION
	// TÄRKEITÄ PIIRTEITÄ
	private double saldo;
	// ATTRIBUUTTIEN JÄLKEEN TULEE KONSTRUKTORIT. KONSTRUKTORI ON VÄHÄN KUIN METODI
	// MUTTA SE EI PALAUTA MITÄÄN JA SITÄ KUTSUTAAN VAIN OLION LUONNIN YHTEYDESSÄ
	// KONSTRUKTOREITA ON PARAMETRITÖN KONSTRUKTORI JA PARAMETRILLINEN KONSTRUKTORI
	// PARAMETRITÖN KONSTRUKTORI
	public Tili() {
		saldo = 6000000;
	}
	// PARAMETRILLINEN KONSTRUKTORI
	public Tili(double summa) {
		saldo = summa;
	}
	// LUOKALLA YLEENSÄ ON METODEITA, JOTKA MÄÄRITTÄVÄT
	// TOIMINNALLISUUTTA, ETTÄ MITÄ LUOKASTA TEHDYILLÄ
	// OLIOILLA VOI TEHDÄ
	public void talleta(double summa) {
		saldo = saldo + summa;
	}
	// MÄÄRITETÄÄN TOIMINNALLISUUS NOSTO
	public void nosta(double summa) {
		saldo = saldo - summa;
	}
	// MÄÄRITETÄÄN TOIMINNALLISUUS SALDON HAKEMISEKSI
	// PALAUTTAA DOUBLEN
	public double haeSaldo() {
		return saldo;
	}
}
